# Data concerning bible books
BOOKS = {
    # Old Testament
    "Genesis": "Gen",
    "Exodus": "Exod",
    "Leviticus": "Lev",
    "Numbers": "Num",
    "Deuteronomy": "Deut",
    "Joshua": "Josh",
    "Judges": "Judg",
    "Ruth": "Ruth",
    "1 Samuel": "1Sam",
    "2 Samuel": "2Sam",
    "1 Kings": "1Kgs",
    "2 Kings": "2Kgs",
    "1 Chronicles": "1Chr",
    "2 Chronicles": "2Chr",
    "Ezra": "Ezra",
    "Nehemiah": "Neh",
    "Tobit": "Tob",
    "Judith": "Jdt",  # Judith
    "Esther": "Esth",
    "1 Maccabees": "1Macc",
    "2 Maccabees": "2Macc",
    "Job": "Job",
    "Psalms": "Ps",  # Ps
    "Proverbs": "Prov",
    "Ecclesiastes": "Eccl",
    "Song of Songs": "Song",  # Songs
    "Wisdom": "Wis",
    "Sirach": "Sir",
    "Isaiah": "Isa",
    "Jeremiah": "Jer",
    "Lamentations": "Lam",
    "Baruch": "Bar",
    "Ezekiel": "Ezek",
    "Daniel": "Dan",
    "Hosea": "Hos",
    "Joel": "Joel",
    "Amos": "Amos",
    "Obadiah": "Obad",
    "Jonah": "Jonah",
    "Micah": "Mic",
    "Nahum": "Nah",
    "Habakkuk": "Hab",
    "Zephaniah": "Zeph",
    "Haggai": "Hag",
    "Zechariah": "Zech",
    "Malachi": "Mal",
    # New Testament
    "Matthew": "Matt",
    "Mark": "Mark",
    "Luke": "Luke",
    "John": "John",
    "Acts": "Acts",
    "Romans": "Rom",
    "1 Corinthians": "1Cor",
    "2 Corinthians": "2Cor",
    "Galatians": "Gal",
    "Ephesians": "Eph",
    "Philippians": "Phil",
    "Colossians": "Col",
    "1 Thessalonians": "1Thess",
    "2 Thessalonians": "2Thess",
    "1 Timothy": "1Tim",
    "2 Timothy": "2Tim",
    "Titus": "Titus",
    "Philemon": "Phlm",
    "Hebrews": "Heb",
    "James": "Jas",  # James
    "1 Peter": "1Pet",  # 1 Peter
    "2 Peter": "2Pet",  # 2 Peter
    "1 John": "1John",
    "2 John": "2John",
    "3 John": "3John",
    "Jude": "Jude",
    "Revelation": "Rev",
}

LECTIONARYTOBIBLEGATEWAY = {
    # Old Testament
    "Gen": "GENESIS",
    "Exod": "EXODUS",
    "Lev": "LEVITICUS",
    "Num": "NUMBERS",
    "Deut": "DEUTERONOMY",
    "Josh": "JOSHUA",
    "Judg": "JUDGES",
    "Ruth": "RUTH",
    "1 Sam": "1 SAMUEL",
    "2 Samuel": "2 SAMUEL",
    "1 Kings": "1 KINGS",
    "2 Kings": "2 KINGS",
    "1 Chr": "1 CHRONICLES",
    "2 Chr": "2 CHRONICLES",
    "Ezra": "EZRA",
    "Neh": "NEHEMIAH",
    "Tob": "TOBIT",
    "Judith": "JUDITH",  # Judith
    "Esth": "ESTHER",
    "1 Macc": "1 MACCABEES",
    "2 Macc": "2 MACCABEES",
    "Job": "JOB",
    "Ps": "PSALMS",  # Ps
    "Prov": "PROVERBS",
    "Eccl": "ECCLESIASTES",
    "Songs": "SONG OF SONGS",  # Songs
    "Wis": "WISDOM",
    "Sir": "SIRACH",
    "Isa": "ISAIAH",
    "Jer": "JEREMIAH",
    "Lam": "LAMENTATIONS",
    "Bar": "BARUCH",
    "Ezek": "EZEKIEL",
    "Dan": "DANIEL",
    "Hos": "HOSEA",
    "Joel": "JOEL",
    "Amos": "AMOS",
    "Obad": "OBADIAH",
    "Jonah": "JONAH",
    "Mic": "MICAH",
    "Nah": "NAHUM",
    "Hab": "HABAKKUK",
    "Zeph": "ZEPHANIAH",
    "Hag": "HAGGAI",
    "Zech": "ZECHARIAH",
    "Mal": "MALACHI",
    # New Testament
    "Matt": "MATTHEW",
    "Mark": "MARK",
    "Luke": "LUKE",
    "John": "JOHN",
    "Acts": "ACTS",
    "Rom": "ROMANS",
    "1 Cor": "1 CORINTHIANS",
    "2 Cor": "2 CORINTHIANS",
    "Gal": "GALATIANS",
    "Eph": "EPHESIANS",
    "Phil": "PHILIPPIANS",
    "Col": "COLOSSIANS",
    "1 Thess": "1 THESSALONIANS",
    "2 Thess": "2 THESSALONIANS",
    "1 Tim": "1 TIMOTHY",
    "2 Tim": "2 TIMOTHY",
    "Titus": "TITUS",
    "Phil": "PHILEMON",
    "Heb": "HEBREWS",
    "James": "Jas",  # James
    "1 Peter": "1Pet",  # 1 Peter
    "2 Peter": "2Pet",  # 2 Peter
    "1 John": "1 JOHN",
    "2 John": "2 JOHN",
    "3 John": "3 JOHN",
    "Jude": "JUDE",
    "Rev": "REVELATION",
}

BOOKCHAPTERS = {
    # Old Testament
    "Genesis": 50,
    "Exodus": 40,
    "Leviticus": 27,
    "Numbers": 36,
    "Deuteronomy": 34,
    "Joshua": 24,
    "Judges": 21,
    "Ruth": 4,
    "1 Samuel": 31,
    "2 Samuel": 24,
    "1 Kings": 22,
    "2 Kings": 25,
    "1 Chronicles": 29,
    "2 Chronicles": 36,
    "Ezra": 10,
    "Nehemiah": 13,
    "Tobit": 14,
    "Judith": 16,
    "Esther": 10,
    "1 Maccabees": 16,
    "2 Maccabees": 15,
    "Job": 42,
    "Psalms": 150,
    "Proverbs": 31,
    "Ecclesiastes": 12,
    "Song of Songs": 8,
    "Wisdom": 19,
    "Sirach": 51,
    "Isaiah": 66,
    "Jeremiah": 52,
    "Lamentations": 5,
    "Baruch": 6,
    "Ezekiel": 48,
    "Daniel": 14,
    "Hosea": 14,
    "Joel": 3,
    "Amos": 9,
    "Obadiah": 1,
    "Jonah": 4,
    "Micah": 7,
    "Nahum": 3,
    "Habakkuk": 3,
    "Zephaniah": 3,
    "Haggai": 2,
    "Zechariah": 14,
    "Malachi": 4,
    # New Testament
    "Matthew": 28,
    "Mark": 16,
    "Luke": 24,
    "John": 21,
    "Acts": 28,
    "Romans": 16,
    "1 Corinthians": 16,
    "2 Corinthians": 13,
    "Galatians": 6,
    "Ephesians": 6,
    "Philippians": 4,
    "Colossians": 4,
    "1 Thessalonians": 5,
    "2 Thessalonians": 3,
    "1 Timothy": 6,
    "2 Timothy": 4,
    "Titus": 3,
    "Philemon": 1,
    "Hebrews": 13,
    "James": 5,
    "1 Peter": 5,
    "2 Peter": 3,
    "1 John": 5,
    "2 John": 1,
    "3 John": 1,
    "Jude": 1,
    "Revelation": 22,
}

VERSIONS = []
